[variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://medium-clone-production-a828.up.railway.app"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "mariadb", "coreutils"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "php artisan migrate --force",
  "php artisan db:seed --force",
  "php artisan config:cache",
  "php artisan storage:link",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
